services:
  neo4j:
    image: "neo4j:5.23-community-bullseye"
    volumes:
      - $HOME/.neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687

  spring:
    image: "gradle:8.14.3-jdk21-jammy"
    volumes:
      - .:/home/gradle/app
      - ~/.keystore:/home/gradle/.keystore
    env_file:
      - .env
    environment:
      - GRADLE_USER_HOME=/home/gradle
      - SSL_KEYSTORE=/home/gradle/.keystore
    working_dir: /home/gradle/app
    entrypoint: "gradle bootRun"
    depends_on:
      - neo4j
